### PR TITLE
DirectX12 hook update

### PR DESCRIPTION
**Pull request by PourrezJ**

### CODE REVIEW

**Comment by mlacker** [comment]
what?
no

**Comment by mlacker** [comment]
hay there, nice meet you

**Comment by PourrezJ** [comment]
Sorry, I should have waited until I was completely finished before opening a pull request.
I still have errors once the hook is done.

**Comment by mlacker** [comment]
No need, do you want do.
And another implement dx12 hook too, but not commit yet

**Comment by mlacker** [comment]
We can do this to together,
For now, i already hook dx12 successful, but PresentHook can not be use.

**Comment by PourrezJ** [comment]
What do you mean by "but PresentHook can not be use.", 
It seems to return the right information to me, however.

http://prntscr.com/rnx2x8

**Comment by mlacker** [comment]
nice !

**Comment by PourrezJ** [comment]
If you want contact me on discord "UserException#1969"

**Comment by mlacker** [comment]
got it

**Comment by PourrezJ** [comment]
ExecuteCommandListsHook crash with RDR2

**Comment by mlacker** [comment]
ExecuteCommandListsHook no crash with dx12 sample app.
image

**Pull request merged**
